# Generated by Django 5.1 on 2024-08-27 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commande',
        ),
    ]
