# Generated by Django 5.1 on 2024-08-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='total',
            field=models.CharField(default=3000, max_length=300),
            preserve_default=False,
        ),
    ]
